Updated install docs
mauricext4fs/wordpress-docker pull request #1
Opened 2019-09-20 11:21 UTC by piotrmackiewicz

https://www.pivotaltracker.com/story/show/168656318

2019-09-23 23:55 UTC, mauricext4fs requested changes

2019-09-23 23:55 UTC, mauricext4fs commented on INSTALL.md
> +   - after you install mysql on your local machine remeber to
Installing mysql is not part of this project... telling people to install mysql "locally" which is absolutely not recommend... is plain wrong and they should use a remote mysql server. Doing this would avoid the issue of using "127.0.0.1" and having to explain that docker isolated network wise and 127.0.0.1 does not refers to de same host inside docker. 

However, in case that the user is using a local mysql server (on the same machine) then you can tell them to check what you have wrote... make sure to tell them that we are strongly discouraging them to use a mysql server on their local machine.

2019-09-24 06:35 UTC, piotrmackiewicz commented on INSTALL.md
> +   - after you install mysql on your local machine remeber to
Ok, I moved instruction about mysql setup and finding docker host ip to troubleshooting, adding also note that using local mysql server is not recommended.

2019-09-26 02:38 UTC, mauricext4fs approved these changes

2019-09-26 02:38 UTC, merged